### ISSUE TITLE
Panics seen when using RequestServiceBuilder

### ISSUE THREAD

**Issue by seanpianka** [routerify/routerify#39]
Related to the code in #38 

Original code:
```rust
let mut builder = RequestServiceBuilder::new(server.router())?;
let mut service = builder.build(remote_addr);
if let Err(e) = poll_fn(|ctx| service.poll_ready(ctx)).await {
    panic!("request service is not ready: {}", e);
}
```
New code:
```rust
let mut service = RequestServiceBuilder::new(server.router())?.build(remote_addr);
poll_fn(|ctx| service.poll_ready(ctx))
    .await
    .expect("request service is not ready");
```
The one-million-dollar question is: why does this cause any of the following crashes when I invoke `service.call(req)`?
```rust
---- tests::should_return_200_and_response stdout ----
thread 'tests::should_return_200_and_response' panicked at 'attempt to multiply with overflow', /Users/sepi/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/prog.rs:154:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: regex::prog::Program::approximate_size
   4: regex::dfa::Fsm::approximate_size
   5: regex::dfa::Fsm::cached_state
   6: regex::dfa::Fsm::exec_byte
   7: regex::dfa::Fsm::next_state
   8: regex::exec::ExecNoSync::many_matches_at
   9: regex::re_set::unicode::RegexSet::read_matches_at
  10: regex::re_set::unicode::RegexSet::matches
  11: routerify::router::Router<B,E>::match_regex_set
```
or
```rust
---- tests::should_return_200_and_response stdout ----
thread 'tests::should_return_200_and_response' panicked at 'assertion failed: cls < self.num_byte_classes', /Users/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1694:9
stack backtrace:
   0: std::panicking::begin_panic
   1: regex::dfa::Transitions::next_unchecked
   2: regex::exec::ExecNoSync::many_matches_at
   3: regex::re_set::unicode::RegexSet::read_matches_at
   4: regex::re_set::unicode::RegexSet::matches
   5: routerify::router::Router<B,E>::match_regex_set
```
or
```rust
project_bin_lambda-b270965688c558eb(84237,0x70000e0f5000) malloc: *** error for object 0x32: pointer being freed was not allocated
project_bin_lambda-b270965688c558eb(84237,0x70000e0f5000) malloc: *** set a breakpoint in malloc_error_break to debug
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6
```

The crash is eventually caused by invoking the method `service.call(req)`. That function uses some `unsafe` apparently for performance, and essentially performs the following:
```rust
fn call(&mut self, mut req: Request<hyper::Body>) -> Self::Future {
    let router = unsafe { &mut *self.router };
    let target_path = percent_decode(req.uri().path())?;
    let fut = async move {
        router.process(target_path).await
    };
    Box::pin(fut)
}
```
I've absolutely no idea why reducing the builder calls from two separate `let`'s to one is causing this problem.

**Comment by seanpianka** [comment]
@Aetf Apologies for the ping, but do you have any insight into why modifying the `RequestServiceBuilder` calls to be chained / fluent could cause this sort of memory unsafety error?

If I apply the commit that makes the above code changes, it reliably crashes with one of three errors I posted, and seems to occur during regex-matching during the router's `process` method.

**Comment by Aetf** [comment]
This is actually a memory lifetime issue. I should've document this in the first place. You need to keep builder alive when using the service, because the builder is the owner of the Router object, and the RequestService only takes a non-owning pointer to the Router object without any type-level lifetime annotation, thus the unsafe block.

I did it this way bacause I don't want to introduce changes to the RequestService to change its type. Ideally, it should be RequestService<'a>, and take a reference to the Router rather than a raw pointer.

But things are more complex than this: the RouterService is expected to produce one RequestService per connection (if I understand hyper doc correctly), so there is inherently a question about whether a Router reference can be shared potentially across threads. So I'm not even sure if the original code is sound.

Anyway, I didn't want to go down this rabbit hole for my simply use case, so I just kept the raw pointer. Now think about it, maybe RequestServiceBuilder::build should be unsafe because it requires the user to ensure the produced RequestService doesn't outlive the builder.

**Comment by seanpianka** [comment]
Thank you for this excellent analysis and your timely response. This totally clarifies the issue and explains why turning two lines into one is not as harmless as it looks, since it shortens the lifetime of the builder and router.

On master is currently a 2.0.0-beta version (a bump of the major version) of Routerify that contains breaking changes to the public API. Before v2 exits beta, I will try to get the `RequestService<'a>` changes into #38, and we can consider marking the builder as `unsafe`...

> the RouterService is expected to produce one RequestService per connection (if I understand hyper doc correctly), so there is inherently a question about whether a Router reference can be shared potentially across threads. So I'm not even sure if the original code is sound.

Could you clarify your soundness concern? i.e. the original / current Routerify implementation may not be sound? 😓

**Comment by Aetf** [comment]
If you can get `RequestService<'a>` working, there's no need for the builder to be `unsafe` then. I'm just saying if `RequestService<'a>` turns out to be hard to implement, then `unsafe` could be a short-term plan.

For the current Routerify implementation, `RouterService` is a [`MakeService`](https://docs.rs/hyper/0.14.2/hyper/service/index.html#makeservice) passed to `Server::bind(&addr).serve(router_service)`,
> Since a Service is bound to a single connection, a Server needs a way to make them as it accepts connections. This is what a MakeService does.

So essentially `RouterService` produces one `RequestService` per connection, and the `Router` object inside `RouterService` is shared via a raw pointer in many `RequestService`s.

Then in `RequestService::call`, the raw pointer is dereferenced as a mutable reference: `let router = unsafe { &mut *self.router };`, but there is no guarantee that this is the only `&mut Router`, and there's a risk of having multiple mutable references because there may be multiple `RequestService` handling multiple connections at the same time (for example in a multi-threaded async executor).

**Comment by seanpianka** [comment]
Closing this as the usage of `unsafe` has been removed from Routerify, and the PR for adding RequestServiceBuilder has been rebased to use these new changes.
