### ISSUE TITLE
Capability to return Response from Pre Middleware

### ISSUE THREAD

**Issue by UndefinedBHVR** [routerify/routerify#42]
So, as far as I can tell, there's no way for a pre middleware to return a response via `Response<Body>`. This seems like something that'd be useful in a fair for scenarios, for example:

Say I have an authentication middleware for an API, if the user provided an expired token, the API could return an application/json response like the following:
```json
{"status": 200, "response": "The Authentication Token provided has expired."}
```

The introduction of this would most likely be a breaking change. So further discussion of implementation would be required. 

Edit: This would technically be covered by the existing Error Handler system, though the constraint of using `std::io::Error` over `std::error::Error` makes the existence of this feature justifiable.

**Comment by UndefinedBHVR** [comment]
Closing as unneeded, just remembered the existence of the error handler function for the builder. Sorry!

**Comment by gsserge** [comment]
There's no constraint on `std::io::Error`.

When defining a **router** and **handlers**, you can pick an error type that is most convenient for you. It can be `Box<dyn std::error::Error + Sync + Send + 'static>`, `anyhow::Error`, `routerify::Error` (although I'd advise against that), or your own custom error. Basically anything that can be converted into `Box<dyn std::error::Error + Sync + Send + 'static>`.

For example, let's define a simple custom error type `MyError` using [thiserror](https://docs.rs/thiserror/1.0.23/thiserror/). I assume you have a function that does the actual auth check, say `check_auth()`.

```rust
use thiserror::Error;

#[derive(Debug, Error, Clone)]
enum MyError {
   #[error("auth error")]
    Auth(String),
}

async fn auth_middleware(req: Request<Body>) -> Result<Request<Body>, Error> {
    // Error out if the auth check fails. This error should be captured in the error handler.
    check_auth(&req).await.map_err(|err| MyError::Auth(err.to_string()))?;
    Ok(req)
}

async fn hello(req: Request<Body>) -> Result<Response<Body>, MyError> {
    Ok(Response::new("Hello".into()))
}

fn router() -> Router<Body, MyError> {
    Router::builder()
        .middleware(Middleware::pre(auth))
        .get("/", hello)
        .err_handler(error_handler) // defined later
        .build()
        .unwrap()
}
```

Now, the second step is to define the error handler. And here you are forced to deal with `routerify::Error`. That was a point of confusion for me when I was just starting out with routerify - no matter what error type router and handlers are using, the error handler is **fixed** to deal with `routerify::Error`. I strongly advise you to use the just released 2.0.0-beta-2 version, because there `routerify::Error` is an enum with each variant holding the boxed error from a particular routing stage that failed (regex match, pre middleware, handlers, etc). In this particular case you are interested in the `HandlePreMiddlewareRequest`.

`HandlePreMiddlewareRequest` holds a boxed error which you should first downcast to `MyError` and then match and return whatever you like. Something like this (I haven't actually compiled it, but the idea works):

```rust
async fn error_handler(err: routerify::Error) -> Response<Body> {
    // Extract pre middleware error.
    if let routerify::Error::HandlePreMiddlewareRequest(err, _) = err {
        // Downcast boxed to MyError.
        if let Some(err) = err.downcast_ref::<MyError>() {
            // Finally, you can match on MyError.
           if let MyError::Auth(_msg) = err {
                   return Response::builder()
                       // You used OK in your example and I'm keeping it here, but to me 401 Unauthorized
                       // makes more sense.
                       .status(StatusCode::OK)
                       .body(Body::from("The Authentication Token provided has expired."))
                       .unwrap();
           }
        }
    } 

    Response::builder()
        .status(StatusCode::INTERNAL_SERVER_ERROR)
        .body(Body::from("Something went wrong"))
        .unwrap()
}
```

**Comment by UndefinedBHVR** [comment]
> There's no constraint on `std::io::Error`.

Ah, I guess I assumed it was because of the example handler using it, alright. That makes things easier then, thank you!
I've already got an error handler setup, I'll go ahead and update to the latest branch and use `routerify::Error` then, thank you!

Closing this issue.

**Comment by gsserge** [comment]
Docs and an example are in https://github.com/routerify/routerify/pull/52
