### ISSUE TITLE
Road to a 2.0.0 Release

### ISSUE THREAD

**Issue by seanpianka** [routerify/routerify#53]
I'm opening this issue as an extension of [one of my earlier comments](https://github.com/routerify/routerify/pull/35#issuecomment-763379218). 

Here's what I consider the items that block a full 2.0.0 (non-beta) release:

1. ~~Merge #38~~
1. ~~Update [the benchmarks](https://github.com/routerify/routerify-benchmark)~~

Feel free to suggest other items that should be included for a new major version release.

Edit: Items moved to after a new major version release:

1. Implement #33 then close #6
1. Close or concretize #13

**Comment by gsserge** [comment]
(2) and (4) are almost done.

(1) would be great. I've run into a problem of dealing manually with query strings and cookies lately, and we can definitely improve on that by having more `RequestExt` convenience methods. However, I don't think we should block the release because of that. New methods are not breaking changes and we can safely introduce them in 2.1.

As for (3), I do not have enough knowledge yet to judge wether that would be a breaking change or not. But I'd say do not hold back the release.

**Comment by seanpianka** [comment]
I've updated the list based on your suggestions, so there's only one small item remaining before the next big release!

**Comment by gsserge** [comment]
> I've updated the list based on your suggestions, so there's only one small item remaining before the next big release!

What small item?

**Comment by seanpianka** [comment]
I was referring to #38 at the time of that comment, but it's merged now. We're ready for a new release!

**Comment by gsserge** [comment]
Maybe one final beta just in case? ;)

**Comment by rousan** [comment]
sure, let's make beta 5 release before 2.0.0 major version.

**Comment by NikosEfthias** [comment]
I have tried to  migrate to 2.0 lates beta but I noticed a couple simple things broke such as error handling.
In particular I used `Eror::new` and `Error::wrap` heavily. Which is not compatible with the new enum based Error api however I think we can introduce a Custom variant and still make the code backwards compatible. 
What do you guys think? I can create a pr for this if all agree  @rousan @gsserge @seanpianka

**Comment by gsserge** [comment]
@NikosEfthias can you demonstrate how this custom enum would look like with a code snippet?

**Comment by NikosEfthias** [comment]
we also should ban using of scoped prefixes to prevent unintended bugs.
for instance user might have a `/api/` scope and a `/api/login` endpoint outside of the scope
currently if I understand correctly `/api/login` will be effected by the middlewares of `/api` since afterr flattening theres no way to distinguish between two. 
This also sound like a fairly simple fix by possibly using const functions at compiletime 
Since theres no correct way to use this we can check routes and if theres a route mathing a scope prefix we could panic so user knows this is not allowed and redesigns the parts possibly adding the exception within the middleware rather then creating a unscoped version

**Comment by seanpianka** [comment]
@NikosEfthias What exactly is the issue? Please post a code example demonstrating the problem.

**Comment by gsserge** [comment]
> @NikosEfthias What exactly is the issue? Please post a code example demonstrating the problem.

@seanpianka see https://github.com/routerify/routerify/issues/58

We should probably get this fixed before 2.0.

**Comment by gsserge** [comment]
@seanpianka I think we can finally cut 2.0 after https://github.com/routerify/routerify/pull/57 and https://github.com/routerify/routerify/pull/59 are sorted. With one more beta first of course :)

**Comment by gsserge** [comment]
@seanpianka will you have time to look at the PRs?

**Comment by gsserge** [comment]
I think we are good to go with 2.0

**Comment by rousan** [comment]
Releasing 2.0.0 .......

**Comment by rousan** [comment]
@gsserge, can you please send me the release notes for major release 2.0.0 in following format:

```txt
Improvements
- item 1
- item2

Bugfixes:
- item1
- item2
```

**Comment by gsserge** [comment]
@rousan sure!

Improvements:
- No more usage of `unsafe`.
- Update to Tokio 1 and Hyper 0.14.
- RequestServiceBuilder (useful for e.g. AWS Lambda).
- Improved error handling.
- Per request contexts.

Bugfixes:
- Convert empty paths to / instead of panicking.
- Scoped middleware should not be applied to unscoped routes with the same prefix.
- When pre middleware fails, correctly propagate router `data` to the error handler and then execute post middleware.

**Comment by rousan** [comment]
We've released v2.0.0 finally. 🎉🎉🎉🎉
