### ISSUE TITLE
The performance of routeify is poor?

### ISSUE THREAD

**Issue by kingluo** [routerify/routerify#77]
I run warp and routerify and use wrk to test.

The server and client are in different machines.

Each machine has two CPUs.

The code of routerify:

```rust
use hyper::{Body, Request, Response, Server};
use routerify::prelude::*;
use routerify::{Router, RouterService};
use std::{convert::Infallible, net::SocketAddr};

async fn hello_handler(req: Request<Body>) -> Result<Response<Body>, Infallible> {
    let name = req.param("name").unwrap();
    Ok(Response::new(Body::from(format!("Hello {}", name))))
}

fn router() -> Router<Body, Infallible> {
    Router::builder()
        .get("/hello/:name", hello_handler)
        .build()
        .unwrap()
}

#[tokio::main]
async fn main() {
    let router = router();

    // Create a Service from the router above to handle incoming requests.
    let service = RouterService::new(router).unwrap();

    // The address on which the server will be listening.
    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));

    // Create a server by passing the created service to `.serve` method.
    let server = Server::bind(&addr).serve(service);

    println!("App is running on: {}", addr);
    if let Err(err) = server.await {
        eprintln!("Server error: {}", err);
    }
}
```

The code of warp:

```rust
use warp::Filter;

#[tokio::main]
async fn main() {
    // GET /hello/warp => 200 OK with body "Hello, warp!"
    let hello = warp::path!("hello" / String).map(|name| format!("Hello {}", name));

    warp::serve(hello).run(([0, 0, 0, 0], 8080)).await;
}
```

```
./wrk -t2 -c400 -d60s http://172.22.86.216:8080/hello/world
```

The output of warp:
```
Running 1m test @ http://172.22.86.216:8080/hello/world
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.24ms   10.74ms 110.27ms   86.64%
    Req/Sec    40.64k     1.26k   44.81k    67.92%
  4853142 requests in 1.00m, 592.42MB read
Requests/sec:  80832.08
Transfer/sec:      9.87MB

```

The output of routeify:
```
Running 1m test @ http://172.22.86.216:8080/hello/world
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.05ms   15.23ms 147.93ms   85.50%
    Req/Sec    28.27k   748.89    32.38k    73.92%
  3376180 requests in 1.00m, 383.15MB read
Requests/sec:  56246.81
Transfer/sec:      6.38MB

```

However, the wrk side of CPU is 110% for routerify, and the wrk side of CPU is 150% for warp.
On the server-side, both are almost 200%.

Does it seem that warp is far better than routeify?

**Comment by gsserge** [comment]
Internal design of warp and routerify is quite different. warp uses a number of advanced techniques, like compiled time polymorphism via generics and macros, which allows for a big chunk of request processing work to be performed at compile time. It allows for the performance that is as close as possible to pure Hyper. The downside is usually longer compile times and internal complexity. 

Routerify, on the other hand, has very simple and straightforward design for an HTTP router. It does a number of allocations, enforced by async rust and futures, uses Arc's to provide request contexts, params and shared state, and does not resort to unsafe code to make this super fast. All this combined obviously makes it slower than pure Hyper or warp. But that's ok, because the performance of any realistic API is usually bound not by URL dispatch or request processing times, but by talking to dependencies like databases and message queues - there's little use of shaving off microseconds when your db calls will be in the order of tens of milliseconds.

As a side note, phrases like "poor" and "far better" might come across as somewhat judgemental, even if not intended. For most people the difference between warp and Routerify, or similar frameworks like Tide, is not in requests per second, but in ergonomics. Not everyone, myself included, likes to model their API as combinators, preferring familiar and straightforward approach inspired years ago by Sinatra and similar frameworks instead.

**Comment by kingluo** [comment]
I am just curious why routeify is slower than warp since routeify uses RegexSet.

**Comment by gsserge** [comment]
URL matching contributes next to nothing to the request processing time. Main contributors are Arc's and allocations.

**Comment by seanpianka** [comment]
@gsserge Do you see a path forward to reduce allocations and use of Arcs without introducing unsafe code again? I certainly agree correctness and simplicity (for maintenance and users) can be a desireable trade-off with a score in a req/s benchmark, however performance improvements in Routerify translate to savings for all the downstream projects. 

Related, as @NikosEfthias has mentioned in the 2.x+ discussion, the Routerify start-up process could benefit from a simpler entrypoint.

**Comment by kingluo** [comment]
I tried to add 100 URL with random names to the routing of warp and routerify, and I found that routerify is better than warp.

```
=========
warp
wrk 60% cpu, warp 200% cpu

Running 1m test @ http://172.22.86.216:8080/hello/world
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    16.75ms   17.16ms 179.01ms   88.22%
    Req/Sec    15.23k   381.80    17.39k    75.33%
  1818579 requests in 1.00m, 221.99MB read
Requests/sec:  30296.78
Transfer/sec:      3.70MB

=============
routefiy
wrk 150% cpu, routefiy 200% cpu

root@test002:~/wrk# ./wrk -t2 -c400 -d60s http://172.22.86.216:8080/hello/world
Running 1m test @ http://172.22.86.216:8080/hello/world
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.54ms   11.47ms 117.56ms   85.55%
    Req/Sec    32.94k     0.93k   39.64k    76.00%
  3932798 requests in 1.00m, 446.32MB read
Requests/sec:  65523.71
Transfer/sec:      7.44MB
```

Maybe it's due to linear scan upon URL of warp, while routerify uses Regexset for url matching.

**Comment by seanpianka** [comment]
Our original consensus around ensuring soundness in Routerify's implementation was to remove usage of `unsafe`. This resulted in new allocations and use of Arcs to share state. 

Routerify does not fall as far along the line of compile-time tradeoffs as Warp. Their use of "compiled time polymorphism via generics and macros" (as @gsserge explained) improves the resulting score from these types of benchmarks. 

I will close this issue for now. Please feel free to start a discussion about a path forward to reducing allocations in Routerify, without re-introducing `unsafe` [here](https://github.com/routerify/routerify/discussions/new).
