### ISSUE TITLE
Removing X-POWERED-BY Header

### ISSUE THREAD

**Issue by Selyatin** [routerify/routerify#90]
How can I remove this header without adding an extra middleware? I don't wanna reveal any kind of information related to the software that is running on the server.

**Comment by rousan** [comment]
@Selyatin, only way to remove this is to attach a middleware. You are welcome to open a pull request to configure this.

**Comment by Selyatin** [comment]
#91

**Comment by gsserge** [comment]
As I have mentioned in the PR, I'd like to remove this header.

**Comment by seanpianka** [comment]
I am also in favor of the outright removal of this header. I'd prefer to offer a separate middleware crate, similar to routerify-cors, which injects the header only if such advertisement is desired by the application developer. 

Users could pull in the advertisement header middleware if desired, but otherwise we would not include it. This would appeal to security-conscious users by default who may not want to expose any of their application's implementation details to HTTP clients.

**Comment by rousan** [comment]
@seanpianka, Actually, I added this header by default as inspiration from the javascript framework [expressjs](https://expressjs.com/). I agree to get rid of it completely, and the developer can add it through a middleware if they want to show.
